### ISSUE TITLE
Allow multiple "key" arguments

### ISSUE THREAD

**Issue by DaemonBeast** [plexidev/quick.db#175]
**Is your feature request related to a problem? Please describe.**
When accessing the database, I am constantly using the dot notation to access nested properties. However, this becomes a nuisance, as I often have to use a template literal to form the path (e.g. ``db.set(`${var1}.${var2}.${var3}`, var4);``).

**Describe the solution you'd like.**
It would be extremely useful if the functions accepted "multiple keys" (e.g. `db.set(var1, var2, var3, var4);`). This would be equivalent to ``db.set(`${var1}.${var2}.${var3}`, var4);`` with the added bonus that no string manipulation has to be done and it looks a lot more readable.

**Describe alternatives you've considered.**
An alternative solution could be to allow an array to be passed as the "key" argument (e.g. `db.set([var1, var2, var3], var4)`).

**Comment by Umut-Ozkan** [comment]
impossible, because better-sqlite3 uses a table, you need to open more keys to do this.

**Comment by Zelak312** [comment]
I am still unsure if this will be in the new version of quick.db(9.0.0).
Instead I would recommend a quick little function that would do the string manipulation for you so you.
