### ISSUE TITLE
Add a "remove" function

### ISSUE THREAD

**Issue by DaemonBeast** [plexidev/quick.db#176]
**Is your feature request related to a problem? Please describe.**
I often work with arrays and as a result, I often use the [`.push()`](https://quickdb.js.org/overview/docs#push) function. However, it becomes harder when trying to remove an item from an array, as there is no function to remove specific items.

**Describe the solution you'd like.**
It would be very useful if there was a `remove()` function that removes one or more specified values from an array (e.g. `db.remove('somearray', 'aValue');`). Multiple values to be removed can be specified as extra arguments (e.g. `db.remove('somearray', 'aValue', 'anotherValue', 'stillGoing');`).

**Describe alternatives you've considered.**
The function could accept an array as the second argument (e.g. `db.remove('somearray', ['aValue', 'anotherValue', 'stillGoing']);`) instead of extra arguments.

**Comment by Loom4k** [comment]
There is already a very similar function named `delete`. I think this is what you are looking for 
```js
db.get('myUser')
// -> { guild: null, balance: 500 }

db.delete('myUser.balance')
// -> true

db.get('myUser')
// -> { guild: null }```

**Comment by lorencerri** [comment]
See 735cf11
