### ISSUE TITLE
Suggestion: Add db.pull() method

### ISSUE THREAD

**Issue by ririko5834** [plexidev/quick.db#185]
**Hi, can you please add db.pull() method?**
I have data in array but i want to remove string from array.
```js
db.push('userInfo.items', 'Watch')
// -> { difficulty: 'Easy', items: ['Sword', 'Watch'], balance: 500 }
```
For example i want to remove Sword from userInfo.items
```js
db.pull("userInfo.items", "Sword"); 
// -> { difficulty: 'Easy', items: ['Watch'], balance: 500 }
```
Can you please send me example code how can i do it?

I think that **db.pull()** will be helpful also for others. Please add it

**Comment by brndto** [comment]
You should be able to extend the wrapper for push and adjust it to filter/remove the data instead of add the new data

**Comment by ItzMeRM** [comment]
@ririko5834 You can use **[quick.db-prototypes](https://www.npmjs.com/package/quick.db-prototypes)** for that.

**Example:**

\`\`\`js
const db = require("quick.db");
require("quick.db-prototypes")(db);

// now you can use methods like db.pull, db.startsWith and more
db.push('items', 'Watch')
// -> ['Sword', 'Watch']

db.pull("items", "Sword"); 
// -> ['Watch']
\`\`\`

**Comment by ItzMeRM** [comment]
@ririko5834 You can use **[quick.db-prototypes](https://www.npmjs.com/package/quick.db-prototypes)** for that.

**Example:**

```js
const db = require("quick.db");
require("quick.db-prototypes")(db);

// now you can use methods like db.pull, db.startsWith and more
db.push('items', 'Watch')
// -> ['Sword', 'Watch']

db.pull("items", "Sword"); 
// -> ['Watch']
```

**Comment by lorencerri** [comment]
See 735cf11
