### ISSUE TITLE
Installation failed due to missing file

### ISSUE THREAD

**Issue by unkn0wnF** [plexidev/quick.db#214]
**Describe the bug**
When installing quick.db it throws an error saying a file can't be found:
```npm WARN tarball tarball data for bindings@https://registry.npmjs.org/bindings/-/bindings-1.5.0.tgz (sha512-p2q/t/mhvuOj/UeLlV6566GD/guowlr0hHxClI0W9m7MWYkL1F0hLo+0Aexs9HSPCtR1SXQ0TD3MMKrXZajbiQ==) seems to be corrupted. Trying again.
npm WARN tarball tarball data for bindings@https://registry.npmjs.org/bindings/-/bindings-1.5.0.tgz (sha512-p2q/t/mhvuOj/UeLlV6566GD/guowlr0hHxClI0W9m7MWYkL1F0hLo+0Aexs9HSPCtR1SXQ0TD3MMKrXZajbiQ==) seems to be corrupted. Trying again.
npm ERR! code ENOENT
npm ERR! syscall lstat
npm ERR! path C:\Users\ascen\AppData\Local\npm-cache\_cacache\content-v2\sha512\a7\6a\bfb7f9a1bee3a3fd478b955eb9eba183fe0ba8c25af4847c42948d16f66ecc59890bd45d212e8fb401ec6cf4748f0ad4754974344c3dcc30aad765a8db89
npm ERR! errno -4058
npm ERR! enoent ENOENT: no such file or directory, lstat 'C:\Users\ascen\AppData\Local\npm-cache\_cacache\content-v2\sha512\a7\6a\bfb7f9a1bee3a3fd478b955eb9eba183fe0ba8c25af4847c42948d16f66ecc59890bd45d212e8fb401ec6cf4748f0ad4754974344c3dcc30aad765a8db89'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent
```

**To Reproduce**
1. Go to the terminal on Visual Studio Code
2. Run these steps for Windows: https://github.com/JoshuaWise/better-sqlite3/blob/master/docs/troubleshooting.md
3. Run `npm i quick.db`

**Expected behavior**
The errors will immediately appear in the terminal.

**Screenshots**
![image](https://user-images.githubusercontent.com/72182515/126915764-8bbc60a7-13ef-4962-982b-a3edc533b5ad.png)

**Desktop (please complete the following information):**
 - OS: Microsoft Windows 10 Home
 - Browser: Chrome
 - Version: Unsure what version is being asked for

**Additional context**
When I tried importing the quick.db module it showed an error:
`File 'c:/Users/ascen/OneDrive/Documents/Programming/Packages/MidnightJS/node_modules/quick.db/index.d.ts' is not a module`

**Comment by Loom4k** [comment]
I think there is a problem with your npm/nodejs installation. I would reccomend re-downloading both of these and test downloading again.
