### ISSUE TITLE
[BUG] Snippet in the README.md ain't working

### ISSUE THREAD

**Issue by Xander1233** [plexidev/quick.db#215]
**Describe the bug**
Snippet in the readme ain't working

**Expected behavior**
Snippet creates a quick.db instance with the file that is passed

**Screenshots**
https://cdn.xndr.tech/u/wwix28X.png

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Node version: v14.6.0

**Comment by Loom4k** [comment]
If you are not using another database program, there is no need to specify the .sqlite file you want the database to be written on. You can simply remove the db() function line and it will manage the files automatically for you.

**Comment by Fabian9799** [comment]
What would i need to do if i want it in a special directory?
I don't want the sqlite file in the root folder of my project.

**Comment by loom4k** [comment]
I don't really know. I would recommend using other tools if you wanna stick with SQL data storage. quick.db is not well done for big projects. Try something like MySQL maybe?

**Comment by Fabian9799** [comment]
I don't really need it for a big project. Just the way im deploying it requires me to define a persistent folder where all changing data is saved.
According to the readme i should be able to use ``const db = quickdb('./json.sqlite');`` which doesn't seem to work

**Comment by Zelak312** [comment]
The snippet you are referencing is from the ^8.0.0 version of quick.db. Unfortunately the npm version is still at 7.1.3 which doesn't have the database function hence why you receive this error.

You can always install from the github main branch or wait for the 9.0.0 version which also has this feature.
