### ISSUE TITLE
Not editing "json.sqlite" file

### ISSUE THREAD

**Issue by cryptosbyte** [plexidev/quick.db#217]
I am running a Linux Debian 10 machine to run my backend server, which uses `quick.db`; the file `json.sqlite` is created but it is not edited/appended by `BetterSqlite3` or `quick.db`. My main code is in the `~/src/` folder and the modules are in `~/node_modules/`.

Although, It works 100% well on the node REPL.

![image](https://user-images.githubusercontent.com/74561974/136100191-69924add-e251-4436-b2ef-4b2a4dbe41fa.png)

**Comment by Zelak312** [comment]
Can you check the file size?
This json.sqlite file is a binary file and sometimes vscode doesn't let you open it
