### ISSUE TITLE
Remote MySQL

### ISSUE THREAD

**Issue by ririko5834** [plexidev/quick.db#224]
**Is your feature request related to a problem? Please describe.**
File system on replit.com is ephemeral, so data from json.sqlite file are removed itself when repl is restarted and moved to new physical server. They do this with repls more times a day.

**Describe the solution you'd like**
Add option to provide remote MySQL database details that will be used instead of .sqlite file.

**Describe alternatives you've considered**
Make second package for it?

**Additional context**

**Comment by abdooo9** [comment]
Use [mysql-database](https://mysql-db.cloud/)

**Comment by Zelak312** [comment]
The next quick.db version will support multiple drivers. The community will be able to create drivers for any type of database including mysql.

**Comment by ririko5834** [comment]
I hope that the community will create drivers for MySQL, MongoDB and others.
This way quick.db could be a universal database that will fit most of the local and remote databases that are used.

**Comment by abdooo9** [comment]
For MongoDB You can use quickmongo.db
For MySQL You can use mysql-databases

**Comment by Zelak312** [comment]
I can create them for the release. It will have a default driver using better-sqlite with two optinal ones using MongoDB and MySQL

**Comment by ririko5834** [comment]
Maybe it could also have PostgreSQL and Redis drivers. But ok

**Comment by Zelak312** [comment]
It isn't my responsibility to create all of them. I will be only creating better-sqlite and MySQL. anything else can easily be added if someone makes an other module that you can plug in or if someone makes an other driver directly in quick.db. so me saying it will only have those doesn't mean that is all it will ever have

**Comment by lorencerri** [comment]
See 4b31d88
