### ISSUE TITLE
FR: "Normal" keys if set

### ISSUE THREAD

**Issue by Wolletje01** [plexidev/quick.db#229]
**Is your feature request related to a problem? Please describe.**
I am always frustrated when I have to put emails in my db. Because a . in the key name means that it is going to be a object with that sub key.

Can you please make a way, maybe in the config, that allows to have key with . as a key and not as a sub object thing.

```js
db.set('myUser.balance', "text")
db.get('myUser.balance')
//"text"
// not { balance: "text"}
```
Maybe something like this
const db = QuickDB( key: standarDize ");
idk which name to give

**Comment by Zelak312** [comment]
Added to the dev branch. This will be available in the next minor release soon!
