### ISSUE TITLE
FR: I can't install quick.db

### ISSUE THREAD

**Issue by Aubin-cyber** [plexidev/quick.db#237]
When I try to install quick.db with the command ''npm install quick.db better-sqlite3'' I receive this error: https://pastebin.com/yesD85gJ. 
Here are the logs: https://pastebin.com/wc9Kpyt7
<img width="631" alt="image" src="https://user-images.githubusercontent.com/96922020/167891119-52f1a9f9-f559-4e80-9e44-b73e685e1cb5.png">

**Comment by Wolletje01** [comment]
I cant help with the problem, but FR means feature request. This isnt a FR

**Comment by Zelak312** [comment]
This error comes from installing better-sqlite3 while not having all the requirements from node-gyp.

The node-gyp installation/requirements for windows can be found here https://github.com/nodejs/node-gyp#on-windows
