### ISSUE TITLE
Removing an item from array

### ISSUE THREAD

**Issue by proudparrot2** [plexidev/quick.db#238]
I'm making a blacklist command, so it stores the user's ID in the array. How can I remove an item from an array?

**Comment by rileyscool** [comment]
Try:
`
const db = require("quick.db");
const blacklist = db.get("Blacklist")
blacklist.set(blacklist.splice(mention))
`

**Comment by Zelak312** [comment]
With the new quick.db version 9.x.x the method pull can be used for this. You can checkout the docs for an example
