### ISSUE TITLE
Starts with function

### ISSUE THREAD

**Issue by Xander1233** [plexidev/quick.db#246]
**Is your feature request related to a problem? Please describe.**
It's not, but in my opinion a startsWith function may be very good for many people. Especially for beginners.

**Describe the solution you'd like**
A function called "startsWith" that gets a string and then filters the db for this string and returns all entrys whose key starts with this string.

**Comment by Zelak312** [comment]
It will be planned for 9.1.x if you want to PR it in dev feel free to do it

**Comment by Xander1233** [comment]
Maybe in the near future. Don't have time rn.
