### ISSUE TITLE
[Feature Request] Encryption

### ISSUE THREAD

**Issue by pendragons-code** [plexidev/quick.db#250]
I understand that quick.db is made to ensure a quick and easy to use system for database storage exists. And yes, the feature I am requesting for is kinda overkill, but think of the benefits that people that use quick.db might receive since most people that use this repo/dependency are learning developers that are interested in programming in general. Yes, they may be better off using something pros use but what about those who can learn from it?

**Comment by Zelak312** [comment]
I wouldn't call encryption overkill, most of what is in the database normally isn't encrypted unless it is really personal information that shouldn't be revealed on plain sight like passwords for example.

If you are asking for a function that would automatically encrypt/decrypt while storing or retrieve the value for the database than I wouldn't be saying no to it. There is a lot of stuff to be done before as it would be placed in a quite low priority.

If you are asking about encrypting everything in the database or the sqlite file itself than it is completely out of the scope of this project

Which one of these are you requesting?
Or maybe it's something else?

**Comment by pendragons-code** [comment]
`If you are asking for a function that would automatically encrypt/decrypt while storing or retrieve a specific value in the database than I wouldn't be saying no to it. There is a lot of stuff to be done before as it would be placed in a quite low priority.`

I was thinking about this! :)

**Comment by Zelak312** [comment]
You're welcome.
I will see what I can do for this, I think it will be a great addition to the utility functions that quick.db offers.

**Comment by pendragons-code** [comment]
I hate to be the person that pesters developers, so I apologize if I am being annoying. I understand that the db here is made for quick and easy usage and that talks about encryption are underway. I also understand that the feature is one that is of low priority. However, I would like to ask how soon are we likely to see this feature. Once again, I thank you for reading this.

**Comment by Zelak312** [comment]
Hey, sorry for the extremely late reply.
I was gone for a while and I left the project for a little while to handle stuff on my side.

I am currently back as in the Lead position of this project again so stuff is going to be moving starting tomorrow.

I have no idea how long it will take for this feature, the main plate consit of rewriting tests and pushing a new version. After those, if nothing else comes up more urgent, it will be done.

Again sorry for the wait

**Comment by pendragons-code** [comment]
Holy shit! NICE FEATURES! I saw the logs in the discord server! It is pretty cool to see something like this go so far!

**Comment by Zelak312** [comment]
Hey, Sorry for taking a lot of time for this feature, I had to do a lot of stuff to make quick.db more stable and version 10.0.0 is coming soon which makes it a lot stable.
Fortunately someone added the Encryption feature, I will be making tests for it and it should release either in version 10.0.0 or 10.1.x

You can follow the progress over at this pull request #308

**Comment by pendragons-code** [comment]
NICE!!! Holy cow man! Desoite your tight shedule you guys have done it! I
am amazed by you all.

**Comment by Zelak312** [comment]
Hey, I will be removing the encryption stuff, I don't have time much to work on quick.db and it would make it even harder for me to have to deal with this so unfortunately it will be something the user will have to do by themselves for now. I appologise for going back on my words, I will be closing this issue since I don't plan to add this any time soon with my current time being taken away by other things.
