### ISSUE TITLE
Can you create more than one file 

### ISSUE THREAD

**Issue by ShadowGaming100** [plexidev/quick.db#258]
Can you create more than one file of database if can I have the code 
And one question if I have more than one file than how do I edit the file

ex I have money.sqlite and settings.sqlite 

I earn money I want to be saved in money.sqlite

I am new on this

so please give me the steps/codes

**Comment by Zelak312** [comment]
Yes it's possible you just need to create multiple instances with different path

```js
const { QuickDB } = require('quick.db');
const money = new QuickDB({ filePath: "./money.sqlite" });
const settings = new QuickDB({ filePath: "./settings.sqlite" });
```

**Comment by ShadowGaming100** [comment]
Thanks
