### ISSUE TITLE
Few questions 

### ISSUE THREAD

**Issue by ShadowGaming100** [plexidev/quick.db#259]
I have few more questions 
1. How do I save the data in database (do I need to do any steps to save the data or when running a bot command will save the data)
Ex. Running give money command it will automatically create data for that or I have to do something before that

2. How do I push data
3. How do I pull data
4. How do I get how many database are there
5. How do I pull/push or save data from a file 
Ex I have settings file and money file I want to pull/push from money file data 
6. How to add data in settings file

i am new 
Please give me code/steps

**Comment by ShadowGaming100** [comment]
I don’t see answer for number 5 only

**Comment by Zelak312** [comment]
There is.
Most of quick.db commands are for this.
Set, get, pull, push. They will all save and use the database and there are examples
