### ISSUE TITLE
mySQL update to v8

### ISSUE THREAD

**Issue by FraglyG** [plexidev/quick.db#264]
I love quickdb.js, though it seems I can't use it on hosting services like railway because the underlying mysql isn't up to date and thus doesn't support mysql v8

an update to mysql v8 would be super cool

**Comment by Zelak312** [comment]
Thank your for this. I will be looking into it. I will probably be changing the library quick.db is using correctly

**Comment by Zelak312** [comment]
This should be fixed now!
