### ISSUE TITLE
"Error: connect ETIMEDOUT"

### ISSUE THREAD

**Issue by Sobhan-SRZA** [plexidev/quick.db#313]
When I use MySQLDriver to connect my MySQL server, mysql2 package and MySQLDriver class have bug or problem.
Please help me or fix it.
```
Error: connect ETIMEDOUT
    at PromisePool.query (/home/runner/...../node_modules/mysql2/promise.js:351:22)
    at MySQLDriver.prepare (/home/runner/...../node_modules/quick.db/out/drivers/MySQLDriver.js:36:25)
    at new QuickDB (/home/runner/...../node_modules/quick.db/out/index.js:35:37)
    at module.exports (/home/runner/...../start/4-database.js:24:16) {
  code: 'ETIMEDOUT',
  errno: undefined,
  sql: undefined,
  sqlState: undefined,
  sqlMessage: undefined
}
```

**Comment by Zelak312** [comment]
Hey, that isn't a problem on quick.db's end. We test the connection on every release and I just tested the MySQLDriver again right now to make sure.

ETIMEDOUT happens when it cannot reach the database. make sure the database is running and that the connection options like the ip/hostname and everything else is set correctly

**Comment by Sobhan-SRZA** [comment]
OK Try it again

**Comment by iTsSobhan** [comment]
> Hey, that isn't a problem on quick.db's end. We test the connection on every release and I just tested the MySQLDriver again right now to make sure.
> 
> ETIMEDOUT happens when it cannot reach the database. make sure the database is running and that the connection options like the ip/hostname and everything else is set correctly

It doesn't fixed :(

**Comment by Sobhan-SRZA** [comment]
> Hey, that isn't a problem on quick.db's end. We test the connection on every release and I just tested the MySQLDriver again right now to make sure.
> 
> ETIMEDOUT happens when it cannot reach the database. make sure the database is running and that the connection options like the ip/hostname and everything else is set correctly

It doesn't fixed :(

**Comment by Zelak312** [comment]
I tested the mysql connection myself to make sure it is working. It is in fact working. If you want you could include more information about your setup and also the database version. You are getting a network error. Your connection or database setup is probably wrong. I cannot do much to assist you in verifying those things

**Comment by Sobhan-SRZA** [comment]
OK, thanks for helping👌🏻
