### ISSUE TITLE
Could not connect with mongo driver

### ISSUE THREAD

**Issue by AlloryDante** [plexidev/quick.db#470]
I wrote a benchmarking script for determining writes per second. I wanted to test mongodb capabilities. I had installed the latest mongodb locally and I had tested it with a separated mongoose script to see that its working. The connection to the daemon is successful on mongoose but when I switch to quick.db it is stuck at the await mongoDriver.connect();

```
const { QuickDB, MongoDriver } = require("quick.db");

(async () => {
  const mongoDriver = new MongoDriver("mongodb://localhost/quickdb");
  await mongoDriver.connect();
  const db = new QuickDB({ driver: mongoDriver });
  let writes = 0;

  console.log("Starting Quick.db benchmark... ");

  // Start writing to database
  setInterval(function () {
    db.set(`key${writes}`, "value");
    writes++;
  }, 0);

  // Output write count every second
  setInterval(function () {
    console.log(`${writes} writes per second`);
    writes = 0;
  }, 1000);
})();

```

Any advice?

**Comment by Zelak312** [comment]
Quick.db doesn't support mongoose 7.x yet, If you want to run mongoose 7.x you will have to use the developement branch of quick.db, otherwise, you will have to downgrade mongoose to 6.x

**Comment by AlloryDante** [comment]
Got it chief
