### ISSUE TITLE
[Feature Request] Support for cassandra-driver

### ISSUE THREAD

**Issue by AlloryDante** [plexidev/quick.db#472]
Hello, It would be nice to support Cassandra and Scylla DB by implementing cassandra-driver lib for node. Their db's usually offer higher performance and would be a nice addition to this lib. What do you guys think?

**Comment by Zelak312** [comment]
it's a great idea, thought it need to be kept in mind that quick.db is more geared towards simplicity and ease of use then for performances so even with those drivers it may be slower then a lot of the other alternatives. I am currently working on getting version 10 of quick.db out for now so they may not be done quickly and it may take a while. I am also open on a pull request if you ever want to add them.

**Comment by AlloryDante** [comment]
> it's a great idea, thought it need to be kept in mind that quick.db is more geared towards simplicity and ease of use then for performances so even with those drivers it may be slower then a lot of the other alternatives. I am currently working on getting version 10 of quick.db out for now so they may not be done quickly and it may take a while. I am also open on a pull request if you ever want to add them.

Thanks for sharing interest into this. I would add a PR, but I am not so skilled in development. Thats why for my use case I would need a lot of reads and writes and Scylla can deliver on it with no problem. Off course that having Quick.db as a proxy can lead to serious problems, however it would still outperform any other database providers and as far as the deployment goes, its just one docker run command. To setup mongodb on my ubuntu, I had to run couple of commands to get it started. 
So yeah, hopefully we will see a cassandra-driver support in Quick.db in the future.

**Comment by BasToTheMax** [comment]
This would be nice to have :D
