### ISSUE TITLE
Pulling an object doesnt work

### ISSUE THREAD

**Issue by Ianyourgod** [plexidev/quick.db#519]
**Describe the bug**
When doing array.pull with an object, the object is not pulled.

**To Reproduce**
1. Create an array.
2. Put an object in the array.
3. Save that array to a db. 
4. Use the pull method to try and take the object out of the array.
5. Use db.all to see if it's still in there.

**Expected behavior**
The object should no longer be in the array

**Desktop (please complete the following information):**
-   OS: Ubuntu 22.04.3
-   Browser Firefox
-   Version 9.1.7

**Additional context**
This can probably fixed by not using array.includes when comparing objects.

**Comment by Zelak312** [comment]
![image](https://github.com/plexidev/quick.db/assets/17593965/d05dc228-9bfc-4359-98d5-743432871cbe)

Here is a pircutre of the discord support where it's talking about this.
It's not a quick.db issue, it's how nodejs does object equality.

As suggested, you should either use a function and return true on the index you want to delete or check for a specific property in the object.

I also don't plan on changing the code to check for properties and do deep equality by default. It should be made by the user of the library so it can be more specific and so it doesn't have problems with potential recursive objects

**Comment by Ianyourgod** [comment]
Alright, thank you.
